"""rename department

Revision ID: 6c6b7b0a73ea
Revises: be55e5b114c4
Create Date: 2024-06-27 17:25:51.350056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6b7b0a73ea'
down_revision = 'be55e5b114c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.op.rename_table('departments', 'department')
    # ### end Alembic commands ###
